# Generated by Django 3.2.12 on 2022-06-01 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_episode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='episode',
            new_name='season',
        ),
    ]
