# Generated by Django 3.2.12 on 2022-12-23 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_group_image_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='joined_group_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 12, 23), null=True),
        ),
    ]
