# Generated by Django 3.2.12 on 2022-06-01 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='is_series',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('season_number', models.CharField(max_length=200)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.film')),
            ],
        ),
    ]
