# Generated by Django 3.2.12 on 2022-06-01 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20220601_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('episode_number', models.CharField(max_length=200)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.season')),
            ],
        ),
    ]
