# Generated by Django 3.2.12 on 2022-06-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_film_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='tags',
            field=models.CharField(choices=[('Action', 'Action'), ('Horror', 'horror'), ('Thriller', 'Thriller')], max_length=20),
        ),
    ]
