# Generated by Django 3.2.12 on 2022-06-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_film_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='episode_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='episode_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
