# Generated by Django 3.2.12 on 2022-12-31 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20221230_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='joined_group_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 12, 31), null=True),
        ),
    ]
